apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homebrew-tap
  annotations:
    github.com/project-slug: integromat/homebrew-tap
spec:
  type: library
  lifecycle: experimental
  owner: group:default/labs
  partOfCoreProduct: false
